using Robust.Shared.Prototypes;

namespace Content.Shared.Silicons.Bots;

[Prototype]
public sealed class SecurityThreatSourcePrototype : IPrototype
{
    [IdDataField] public string ID { get; private set; } = default!;

    /// <summary>
    /// The amount of threat generated by an entity with this prototype
    /// </summary>
    [DataField]
    public int Threat;
}
