using Content.Shared.Administration.ParrotMessages;
using Content.Shared.Eui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Administration.UI.ParrotMessages;

[GenerateTypedNameReferences]
public sealed partial class ParrotMessageList : BoxContainer
{
    private void OnRequestRefresh(BaseButton.ButtonEventArgs obj)
    {
        SendRefreshRequest();
    }

    public void UpdateMessageCountText(int messageCount)
    {
        ParrotMessageCountLabel.Text = Loc.GetString("parrot-messages-num-messages", ("messageCount", messageCount));
    }

    private void SendRefreshRequest()
    {
        // SendMessage(new ParrotMessageRefreshMsg());
    }

    private void SendBlockRequest(int messageId)
    {
        // SendMessage(new ParrotMessageBlockChangeMsg(messageId, true));
    }

    private void SendUnblockRequest(int messageId)
    {
        // SendMessage(new ParrotMessageBlockChangeMsg(messageId, false));
    }

    private void SendFilterChangeMsg()
    {
        var filterString = ParrotFilterLineEdit.Text;

        var msg = new ParrotMessageFilterChangeMsg(filterString);

        // SendMessage(msg);
    }

    public ParrotMessageLine AddMessageLine(ExtendedParrotMemory memory)
    {
        var messageLine = new ParrotMessageLine();

        messageLine.SetMessage(memory);

        ParrotMessageContainer.AddChild(messageLine);

        return messageLine;
    }

    public void UpdateMessages(List<ExtendedParrotMemory> parrotMemories)
    {

        UpdateMessageCountText(parrotMemories.Count);

        ParrotMessageContainer.RemoveAllChildren();

        foreach (var memory in parrotMemories)
        {
            var messageLine = AddMessageLine(memory);

            if (memory.Blocked)
            {
                messageLine.ParrotBlockButton.Text = Loc.GetString("parrot-messages-line-unblock");
                messageLine.ParrotBlockButton.ToolTip = Loc.GetString("parrot-messages-line-unblock-tooltip");
                messageLine.ParrotBlockButton.OnPressed += _ =>
                {
                    SendUnblockRequest(memory.MessageId);
                };
                continue;
            }

            messageLine.ParrotBlockButton.OnPressed += _ =>
            {
                SendBlockRequest(memory.MessageId);
            };
        }
    }
}
