using Content.Shared.Administration.ParrotMessages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Administration.UI.ParrotMessages;

[GenerateTypedNameReferences]
public sealed partial class ParrotMessageLine : BoxContainer
{

    public void SetMessage(SharedParrotMessage message)
    {
        ParrotMessageText.Text = message.MessageText;
        ParrotMessagePlayerButton.Text = message.SourcePlayerUserName;
        ParrotMessagePlayerButton.Command = $"openahelp {message.SourcePlayerGuid}";
    }
}
