using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration.ParrotMessages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.ParrotMessages;

[GenerateTypedNameReferences]
public sealed partial class ParrotMessagesWindow : FancyWindow
{
    public ParrotMessagesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateMessageCountText(int messageCount)
    {
        ParrotMessageCountLabel.Text = Loc.GetString("parrot-messages-num-messages", ("messageCount", messageCount));
    }

    public ParrotMessageLine AddMessageLine(SharedParrotMessage message)
    {
        var messageLine = new ParrotMessageLine();

        messageLine.SetMessage(message);

        ParrotMessageContainer.AddChild(messageLine);

        return messageLine;
    }
}
