using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration.ParrotMessages;
using Content.Shared.Eui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.ParrotMessages;

[GenerateTypedNameReferences]
public sealed partial class ParrotMessagesWindow : FancyWindow
{
    public ParrotMessagesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    private ParrotMessageList? GetActiveList()
    {
        var currentActiveTab = MessageTabContainer.CurrentTab;
        var currentActiveChild = MessageTabContainer.GetChild(currentActiveTab);

        if (currentActiveChild is not ParrotMessageList { } messageList)
            return null;

        return messageList;
    }

    public void UpdateMessages(ParrotMessagesEuiState parrotState)
    {
        var activeList = GetActiveList();

        activeList?.UpdateMessages(parrotState.Messages);
    }
}
