using Content.Shared.Administration.ParrotMessages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Administration.UI.ParrotMessages;

[GenerateTypedNameReferences]
public sealed partial class ParrotMessageLine : BoxContainer
{

    public void SetMessage(ExtendedParrotMemory memory)
    {
        ParrotMessageText.Text = memory.MessageText;
        ParrotMessagePlayerButton.Text = memory.SourcePlayerUserName;
        ParrotMessagePlayerButton.Command = $"openahelp {memory.SourcePlayerGuid}";
    }
}
